require('lazy').setup({

  -- require 'plugins/gitsigns',
  require 'plugins/which-key',
  require 'plugins/comment',
  require 'plugins/hop',
  require 'plugins/tree',
  require 'plugins/telescope',
  require 'plugins/lspconfig',
  require 'plugins/winpick',
  require 'plugins/bufdelete',
  require 'plugins/bufexplorer',
  require 'plugins/completion',
  -- require 'plugins/tokyonight',
  require 'plugins/onedarkpro',
  require 'plugins/lualine',
  require 'plugins/vim-fugitive',
  require 'plugins/vim-gitgutter',
  require 'plugins/indent-blankline',
  require 'plugins/surround',
  require 'plugins/aerial',
  require 'plugins/autopairs',
  require 'plugins/terminal',
  require 'plugins/treesitter',
}, {
  ui = {
    icons = {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
