syntax enable
set background=light
set guioptions -=T
if has('win32')
	set guifont=Lucida_Console:h9:cANSI:qDRAFT	
	:nnoremap <F11> :WToggleFullscreen<cr>
else
	set guifont=Lucida\ Console\ Semi-Condensed\ 9
endif
colorscheme zenburn
