set nocompatible
set visualbell
syntax on
set scrolloff=0
set hidden
set number relativenumber
set laststatus=2
set title
set noswapfile
set nobackup
set autoindent
set wildmenu
set shiftwidth=4 tabstop=4 expandtab
set incsearch hlsearch
set ignorecase smartcase
set clipboard^=unnamed,unnamedplus
set undodir=~/vimundo
set textwidth=80
set autochdir

filetype plugin indent on

" if has('win32')
"     set shell=powershell
" else
"     set shell=zsh
" endif
" 

let mapleader = ' '

packadd minpac

call minpac#init({'verbose': 3})
call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('tpope/vim-vinegar')
call minpac#add('tpope/vim-commentary')
call minpac#add('vim-airline/vim-airline')
call minpac#add('jlanzarotta/bufexplorer')
call minpac#add('yegappan/mru')
call minpac#add('kkoenig/wimproved.vim')
call minpac#add('OmniSharp/omnisharp-vim')
call minpac#add('mileszs/ack.vim')
call minpac#add('easymotion/vim-easymotion')
call minpac#add('flazz/vim-colorschemes')

command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
command! PackStatus call minpac#status()

let g:OmniSharp_server_stdio = 1
let g:OmniSharp_start_server = 0
let g:omnisharp_proc_debug = 0
let g:OmniSharp_server_loading_timeout = 60
let g:OmniSharp_timeout = 300
let g:OmniSharp_server_stdio_quickload = 0

augroup omnisharp_commands
    autocmd!

    " Show type information automatically when the cursor stops moving
    autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

    " The following commands are contextual, based on the cursor position.
    autocmd FileType cs nnoremap <buffer> gd :OmniSharpGotoDefinition<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fi :OmniSharpFindImplementations<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fs :OmniSharpFindSymbol<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fu :OmniSharpFindUsages<CR>

    " Finds members in the current buffer
    autocmd FileType cs nnoremap <buffer> <Leader>fm :OmniSharpFindMembers<CR>

    autocmd FileType cs nnoremap <buffer> <Leader>fx :OmniSharpFixUsings<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>tt :OmniSharpTypeLookup<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>dc :OmniSharpDocumentation<CR>
    autocmd FileType cs nnoremap <buffer> <C-\> :OmniSharpSignatureHelp<CR>
    autocmd FileType cs inoremap <buffer> <C-\> <C-o>:OmniSharpSignatureHelp<CR>

    " Navigate up and down by method/property/field
    autocmd FileType cs nnoremap <buffer> <C-k> :OmniSharpNavigateUp<CR>
    autocmd FileType cs nnoremap <buffer> <C-j> :OmniSharpNavigateDown<CR>

    " Find all code errors/warnings for the current solution and populate the quickfix window
    autocmd FileType cs nnoremap <buffer> <Leader>cc :OmniSharpGlobalCodeCheck<CR>
augroup END

nnoremap <Leader>ss :OmniSharpStartServer<CR>
nnoremap <Leader>sp :OmniSharpStopServer<CR>

let g:ackprg = 'ag --nogroup --nocolor --column'

:inoremap jk <esc>

:nnoremap <leader>fr :MRU<cr>

:nnoremap <leader>bk :b#<bar>bd#<CR>
:nnoremap <leader>bl :BufExplorer<CR>
:nnoremap <leader>bq :q<CR>

:nnoremap <leader>h :nohlsearch<CR>

:nnoremap <leader>xs :w<CR>
:nnoremap <leader>xS :wa<CR>
:nnoremap <leader>xc :qa<CR>

autocmd BufRead,BufNewFile *.md setlocal spell
